/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type EtherifyTrackStruct = { addr: string; spotifyLink: string };

export type EtherifyTrackStructOutput = [string, string] & {
  addr: string;
  spotifyLink: string;
};

export interface EtherifyPlaylistInterface extends ethers.utils.Interface {
  functions: {
    "addTrack(string)": FunctionFragment;
    "getPlaylist()": FunctionFragment;
    "getTotalTracks()": FunctionFragment;
    "getTracksByAddress(address)": FunctionFragment;
    "tracksByAddress(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addTrack", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getPlaylist",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalTracks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTracksByAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "tracksByAddress",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addTrack", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPlaylist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTracks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTracksByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tracksByAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface EtherifyPlaylist extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EtherifyPlaylistInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addTrack(
      trackToAdd: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getPlaylist(
      overrides?: CallOverrides
    ): Promise<[EtherifyTrackStructOutput[]]>;

    getTotalTracks(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTracksByAddress(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[EtherifyTrackStructOutput[]]>;

    tracksByAddress(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { addr: string; spotifyLink: string }>;
  };

  addTrack(
    trackToAdd: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getPlaylist(overrides?: CallOverrides): Promise<EtherifyTrackStructOutput[]>;

  getTotalTracks(overrides?: CallOverrides): Promise<BigNumber>;

  getTracksByAddress(
    addr: string,
    overrides?: CallOverrides
  ): Promise<EtherifyTrackStructOutput[]>;

  tracksByAddress(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, string] & { addr: string; spotifyLink: string }>;

  callStatic: {
    addTrack(trackToAdd: string, overrides?: CallOverrides): Promise<void>;

    getPlaylist(
      overrides?: CallOverrides
    ): Promise<EtherifyTrackStructOutput[]>;

    getTotalTracks(overrides?: CallOverrides): Promise<BigNumber>;

    getTracksByAddress(
      addr: string,
      overrides?: CallOverrides
    ): Promise<EtherifyTrackStructOutput[]>;

    tracksByAddress(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { addr: string; spotifyLink: string }>;
  };

  filters: {};

  estimateGas: {
    addTrack(
      trackToAdd: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getPlaylist(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalTracks(overrides?: CallOverrides): Promise<BigNumber>;

    getTracksByAddress(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tracksByAddress(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addTrack(
      trackToAdd: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getPlaylist(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTotalTracks(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTracksByAddress(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tracksByAddress(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
